sudo: required
dist: trusty
language: php

services:
  - mysql

php:
  - 7.2

addons:
  chrome: stable

cache:
  directories:
    - vendor

before_script:
    - cp .env.travis .env
    - mysql -e 'create database homestead_test;'
    - composer self-update
    - travis_retry composer install --no-interaction --prefer-dist --no-suggest
    - php artisan key:generate
    - php artisan serve > /dev/null 2>&1 &
    - php artisan migrate
    - php artisan db:seed
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - php artisan serve &


script:
    - phpunit
    - php artisan dusk