<?php

return [
	'floats' => [
		'Factory New'    => [
			0, 0.07,
		],
		'Minimal Wear'   => [
			0.07, 0.15,
		],
		'Field-Tested'   => [
			0.15, 0.37,
		],
		'Well-Worn'      => [
			0.37, 0.44,
		],
		'Battle-Scarred' => [
			0.44, 1,
		],
	],

	'knives' => [
		'★ Bayonet',
		'★ Bowie Knife',
		'★ Butterfly Knife',
		'★ Falchion Knife',
		'★ Flip Knife',
		'★ Gut Knife',
		'★ Huntsman Knife',
		'★ Karambit',
		'★ M9 Bayonet',
		'★ Navaja Knife',
		'★ Shadow Daggers',
		'★ Stiletto Knife',
		'★ Talon Knife',
		'★ Ursus Knife',
	],

	'name-to-short' => [
		'AK-47'             => 'ak47',
		'AUG'               => 'aug',
		'AWP'               => 'awp',
		'CZ75-Auto'         => 'cz75a',
		'Desert Eagle'      => 'deagle',
		'Dual Berettas'     => 'elite',
		'FAMAS'             => 'famas',
		'Five-SeveN'        => 'fiveseven',
		'G3SG1'             => 'g3sg1',
		'Galil AR'          => 'galilar',
		'Glock-18'          => 'glock',
		'M249'              => 'm249',
		'M4A1-S'            => 'm4a1_silencer',
		'M4A4'              => 'm4a1',
		'MAC-10'            => 'mac10',
		'MAG-7'             => 'mag7',
		'MP5-SD'            => 'mp5sd',
		'MP7'               => 'mp7',
		'MP9'               => 'mp9',
		'Negev'             => 'negev',
		'Nova'              => 'nova',
		'P2000'             => 'hkp2000',
		'P250'              => 'p250',
		'P90'               => 'p90',
		'PP-Bizon'          => 'bizon',
		'R8 Revolver'       => 'revolver',
		'SCAR-20'           => 'scar20',
		'SG 553'            => 'sg556',
		'SSG 08'            => 'ssg08',
		'Sawed-Off'         => 'sawedoff',
		'Tec-9'             => 'tec9',
		'UMP-45'            => 'ump45',
		'USP-S'             => 'usp_silencer',
		'XM1014'            => 'xm1014',
		'★ Bayonet'         => 'bayonet',
		'★ Bowie Knife'     => 'knife_survival_bowie',
		'★ Butterfly Knife' => 'knife_butterfly',
		'★ Falchion Knife'  => 'knife_falchion',
		'★ Flip Knife'      => 'knife_flip',
		'★ Gut Knife'       => 'knife_gut',
		'★ Huntsman Knife'  => 'knife_tactical',
		'★ Karambit'        => 'knife_karambit',
		'★ M9 Bayonet'      => 'knife_m9_bayonet',
		'★ Navaja Knife'    => 'knife_gypsy_jackknife',
		'★ Shadow Daggers'  => 'knife_push',
		'★ Stiletto Knife'  => 'knife_stiletto',
		'★ Talon Knife'     => 'knife_widowmaker',
		'★ Ursus Knife'     => 'knife_ursus',

	],
	'knife-classes' => [
		'knife_karambit'        => '33',
		'knife_m9_bayonet'      => '34',
		'bayonet'               => '35',
		'knife_survival_bowie'  => '36',
		'knife_butterfly'       => '37',
		'knife_flip'            => '38',
		'knife_push'            => '39',
		'knife_tactical'        => '40',
		'knife_falchion'        => '41',
		'knife_gut'             => '42',
		'knife_ursus'           => '43',
		'knife_gypsy_jackknife' => '44',
		'knife_stiletto'        => '45',
		'knife_widowmaker'      => '46',
	],

];
